### ISSUE TITLE
Unable to create CBS volume

### ISSUE THREAD

**Issue by dgivens** [rackspace-cookbooks/rackspacecloud#42]
I'm trying to create and attach a CBS volume. I get the same result when attempting to create it on an instance that has been running for a while or one that is brand new, so I doubt it's a per-instance issue. I thought it may have been the region being lowercase by default, hence the `.upcase` on the region name. Also, the examples need to be updated because current versions of Chef now have `rackspace.region`, instead of `rackspace.cloud.region`.

```
104.239.143.27   * rackspacecloud_cbs[test-n01-carbon] action create_and_attach
104.239.143.27     
104.239.143.27     ================================================================================
104.239.143.27     Error executing action `create_and_attach` on resource 'rackspacecloud_cbs[test-n01-carbon]'
104.239.143.27     ================================================================================
104.239.143.27     
104.239.143.27     RuntimeError
104.239.143.27     ------------
104.239.143.27     unable to locate server in compute API
104.239.143.27     
104.239.143.27     Cookbook Trace:
104.239.143.27     ---------------
104.239.143.27     /var/chef/cache/cookbooks/rackspacecloud/providers/cbs.rb:138:in `locate_server'
104.239.143.27     /var/chef/cache/cookbooks/rackspacecloud/providers/cbs.rb:30:in `load_current_resource'
104.239.143.27     /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:78:in `run_action'
104.239.143.27     /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `block (2 levels) in converge'
104.239.143.27     /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `each'
104.239.143.27     /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `block in converge'
104.239.143.27     /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:105:in `converge'
104.239.143.27     
104.239.143.27     Resource Declaration:
104.239.143.27     ---------------------
104.239.143.27     # In /var/chef/cache/cookbooks/heat-graphite/recipes/cbs.rb
104.239.143.27     
104.239.143.27       9:   rackspacecloud_cbs "#{node['hostname']}-carbon" do
104.239.143.27      10:     type "SSD"
104.239.143.27      11:     size 50
104.239.143.27      12:     rackspace_username rackspace_username
104.239.143.27      13:     rackspace_api_key rackspace_api_key
104.239.143.27      14:     rackspace_region "#{node['rackspace']['region'].upcase}"
104.239.143.27      15:     action :create_and_attach
104.239.143.27      16:   end
104.239.143.27      17: 
104.239.143.27     
104.239.143.27     Compiled Resource:
104.239.143.27     ------------------
104.239.143.27     # Declared in /var/chef/cache/cookbooks/heat-graphite/recipes/cbs.rb:9:in `from_file'
104.239.143.27     
104.239.143.27     rackspacecloud_cbs("test-n01-carbon") do
104.239.143.27       action [:create_and_attach]
104.239.143.27       retries 0
104.239.143.27       retry_delay 2
104.239.143.27       default_guard_interpreter :default
104.239.143.27       declared_type :rackspacecloud_cbs
104.239.143.27       cookbook_name "heat-graphite"
104.239.143.27       recipe_name "cbs"
104.239.143.27       type "SSD"
104.239.143.27       size 50
104.239.143.27       rackspace_username "redacted"
104.239.143.27       rackspace_api_key "redacted"
104.239.143.27       rackspace_region "DFW"
104.239.143.27     end
104.239.143.27     
104.239.143.27     Platform:
104.239.143.27     ---------
104.239.143.27     x86_64-linux
```

**Comment by martinb3** [comment]
Hey @dgivens -- could you provide the cloud server's ID via `nova show` output, as well as the output of `xenstore-read name` on the server? I'm guessing these don't match or the `xenstore-read` command is broken on the instance. Cheers!
